name: Deploy [BUSINESS_NAME] Website
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Client Hosting
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: lavain-lon1.krystal.uk
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        security: strict
        exclude: |
          **/.git*
          **/.git*/**
          **/deploy.sh
          **/README.md
          **/.github/**
